### ISSUE TITLE
训练edit问题

### ISSUE THREAD

**Issue by YuShuTong666** [ByteDance-Seed/Bagel#131]
/home/pytorch/alinux3/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:93: operator(): block: [14322,0,0], thread: [123,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/home/pytorch/alinux3/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:93: operator(): block: [14322,0,0], thread: [124,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/home/pytorch/alinux3/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:93: operator(): block: [14322,0,0], thread: [125,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/home/pytorch/alinux3/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:93: operator(): block: [14322,0,0], thread: [126,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/home/pytorch/alinux3/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:93: operator(): block: [14322,0,0], thread: [127,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
[rank1]:[E606 15:20:10.319952852 ProcessGroupNCCL.cpp:1595] [PG ID 4 PG GUID 10 Rank 1] Process group watchdog thread terminated with exception: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at /home/pytorch/alinux3/pytorch/c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7f22969961c6 in /opt/conda/envs/python3.10.13/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5c (0x7f2296940360 in /opt/conda/envs/python3.10.13/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7f22979e9898 in /opt/conda/envs/python3.10.13/lib/python3.10/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x56 (0x7f2242834636 in /opt/conda/envs/python3.10.13/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0xa0 (0x7f2242839680 in /opt/conda/envs/python3.10.13/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::watchdogHandler() + 0x1ba (0x7f224284316a in /opt/conda/envs/python3.10.13/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14d (0x7f2242844e5d in /opt/conda/envs/python3.10.13/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0xd8b74 (0x7f2313660b74 in /lib64/libstdc++.so.6)
frame #8: <unknown function> + 0x93fb (0x7f2314e9e3fb in /lib64/libpthread.so.0)
frame #9: clone + 0x43 (0x7f2314ba2e83 in /lib64/libc.so.6)

terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG ID 4 PG GUID 10 Rank 1] Process group watchdog thread terminated with exception: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at /home/pytorch/alinux3/pytorch/c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7f22969961c6 in /opt/conda/envs/python3.10.13/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5c (0x7f2296940360 in /opt/conda/envs/python3.10.13/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7f22979e9898 in /opt/conda/envs/python3.10.13/lib/python3.10/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x56 (0x7f2242834636 in /opt/conda/envs/python3.10.13/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0xa0 (0x7f2242839680 in /opt/conda/envs/python3.10.13/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::watchdogHandler() + 0x1ba (0x7f224284316a in /opt/conda/envs/python3.10.13/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14d (0x7f2242844e5d in /opt/conda/envs/python3.10.13/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0xd8b74 (0x7f2313660b74 in /lib64/libstdc++.so.6)
frame #8: <unknown function> + 0x93fb (0x7f2314e9e3fb in /lib64/libpthread.so.0)
frame #9: clone + 0x43 (0x7f2314ba2e83 in /lib64/libc.so.6)

Exception raised from ncclCommWatchdog at /home/pytorch/alinux3/pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1601 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7f22969961c6 in /opt/conda/envs/python3.10.13/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x102288e (0x7f224282288e in /opt/conda/envs/python3.10.13/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0xcd7401 (0x7f22424d7401 in /opt/conda/envs/python3.10.13/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0xd8b74 (0x7f2313660b74 in /lib64/libstdc++.so.6)
frame #4: <unknown function> + 0x93fb (0x7f2314e9e3fb in /lib64/libpthread.so.0)
frame #5: clone + 0x43 (0x7f2314ba2e83 in /lib64/libc.so.6)

**Comment by YuShuTong666** [comment]
用的4*A100，  参数如下
  --freeze_vit TRUE \
  --log_every 1 \
  --lr 2e-5 \
  --num_worker 4 \
  --expected_num_tokens 10240 \
  --max_num_tokens 11520 \
  --max_num_tokens_per_sample 10240\
  --visual_und False\
  --wandb_offline True\
  --auto_resume True\
  --resume_model_only True\
  --finetune_from_ema True\
  --finetune_from_hf True\
  --freeze_und=TRUE\
  --num_replicate 1\
  --num_shard 4\
  --vit_cond_dropout_prob 0\
  --sharding_strategy HYBRID_SHARD\

**Comment by YuShuTong666** [comment]
显然没有，hxd解决了记得教我



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年6月9日(周一) 下午3:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ByteDance-Seed/Bagel] 训练edit问题 (Issue #131)


sunwenzhang1996 left a comment (ByteDance-Seed/Bagel#131)
 
我也遇到这个问题，目前定位到是位置编码那里的问题。你现在解决了么？

**Comment by Andy1621** [comment]
`max_latent_size`是否使用64？

**Comment by FrankYang-17** [comment]
@YuShuTong666 Hi, did u solve it?

**Comment by mattxu98** [comment]
I finetuned Bagel on 2* H20, using `--max_latent_size 64` as instructed and reverted `--vit_max_num_patch_per_side 70` as default, the issue disappeared.
If you decrease `--vit_max_num_patch_per_side 70` to avoid Cuda OOM on smaller GPUs, you may need to change `example.yaml` to ensure that every `max_image_size / image_stride <= vit_max_num_patch_per_side` for every dataset using ViT stream.
