### ISSUE TITLE
CUDA out of memory when evaluating the WISE benchmark.

### ISSUE THREAD

**Issue by Maplebb** [ByteDance-Seed/Bagel#227]
Thank you for you work!
When I generated images adopting the script `run_wise.sh` with 2x 80G H100, it reported the issue "CUDA out of memory". I wonder if something went wrong or it needs more GPU resources?

**Comment by Andy1621** [comment]
Hi! Please try to change the initialization like that in `inference.ipynb`.

**Comment by Maplebb** [comment]
Thx~ I've tried that and it works👍
